#:schema node_modules/wrangler/config-schema.json
name = "r2-consumer-migration"
main = "src/index.ts"
compatibility_date = "2024-10-11"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[queues.consumers]]
  queue = "r2-event-notifications"
  max_batch_size = 10
  max_batch_timeout = 30
  max_retries = 10
